#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn
import Build

include_dirs = """
                 #lib/libavl/include 
                 #lib/libnvpair/include 
                 #lib/libumem/include 
                 #lib/libzfscommon/include 
                 #lib/libzpool/include 
                 #lib/libsolcompat/include
               """.split()

obj = bld.new_task_gen(
        features = 'cc cprogram',
        includes = include_dirs,
        defines = [ '_FILE_OFFSET_BITS=64', 'TEXT_DOMAIN=\"zfs-fuse\"'],
        uselib_local = 'zpool-user zfscommon-user  nvpair-user avl umem solcompat',
        uselib = 'm_lib dl_lib rt_lib pthread_lib z_lib aio_lib',
        name = 'ztest',
        target = 'ztest'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

#bld.add_manual_dependency('zdb', 'Rebuild if this changes')

