#!/bin/bash -x

set -e

version="$1"
[ -z "$version" ] && {
	version=`grep Version zfs-fuse.spec | awk ' { print $2 } '`
	echo $version deduced from specfile
}
[ -z "$version" ] && {
	echo "Could not determine version from specfile"
	exit 1
}

BASE=`basename "$PWD"`
cd ..
cp -R "$BASE" "zfs-fuse-$version"
cd "zfs-fuse-$version"
rm -rf .hg .hgignore .hgtags zfs-fuse*tar.bz2
cd src
scons -c
rm .sconsign.dblite
cd ../..
tar cvjf "zfs-fuse-$version.tar.bz2" "zfs-fuse-$version"
rm -rf "zfs-fuse-$version"
mv "zfs-fuse-$version.tar.bz2" "$BASE"
cd "$BASE"
