#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

include_dirs = """
                 #lib/libavl/include
                 #lib/libumem/include
                 include
                 .
                 """.split()

obj = bld.new_task_gen(
        features = 'cc cstaticlib',
        includes = include_dirs,
        defines = [ '_KERNEL', '_FILE_OFFSET_BITS=64'],
        target = 'libsolkerncompat'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

obj.env['ASFLAGS'] = '-c'

arch = 'i386'

if bld.env['DEST_CPU'] == 'x86_64':
    arch = 'amd64'
    warn('picking up assembly from %s' % arch)

obj.source = obj.source +  [arch + '/atomic.S']
obj.includes = obj.includes +  ['include/' + arch]
