Import('env')

Command("Makefile", [], ["cd lib/libumem && ./configure"])
Command("libumem.a", [Glob('*.c'),'Makefile',Glob('*.h')], ["cd lib/libumem && make && rm -f libumem.a && ln -s .libs/libumem.a"])

