#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

obj = bld.new_task_gen(
        features = 'cc cstaticlib',
        includes = ['include', '.'],
        defines = [ '_FILE_OFFSET_BITS=64'],
        target = 'libumem'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

