Import('env')

objects = Split('libzfs_dataset.c libzfs_util.c libzfs_graph.c libzfs_mount.c libzfs_pool.c libzfs_changelist.c libzfs_config.c libzfs_import.c libzfs_status.c libzfs_sendrecv.c libzfs_zfsfuse.c fletcher.c')
cpppath = Split('./include #lib/libavl/include #lib/libnvpair/include #lib/libumem/include #lib/libzfscommon/include #lib/libzpool/include #lib/libuutil/include #lib/libsolcompat/include #lib/libzfs/include')

env.StaticLibrary('libzfs', objects, CPPPATH = env['CPPPATH'] + cpppath)
