#! /usr/bin/env python
# encoding: utf-8
# Sandeep S Srinivasa, 2009
from Logs import error, debug, warn

include_dirs = """
                include 
                #lib/libavl/include 
                #lib/libnvpair/include 
                #lib/libumem/include 
                #lib/libzfscommon/include 
                #lib/libzpool/include 
                #lib/libuutil/include 
                #lib/libsolcompat/include 
                #lib/libzfs/include
                 """.split()

obj = bld.new_task_gen(
        features = 'cc cstaticlib',
        includes = include_dirs,
        defines = [ '_FILE_OFFSET_BITS=64', 'TEXT_DOMAIN=\"zfs-fuse\"'],
        target = 'zfs'
        )


obj.find_sources_in_dirs('.') # take the sources in the current folder

